[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "edapi"
version = "0.0.2"
dependencies = [
    "requests",
    "python-dotenv",
    "beautifulsoup4"
]
